apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helm.fullname" . }}-secret
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := index .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
