helmDefaults:
  atomic: true
  verify: false
  wait: true
  timeout: 1200
  force: false
  createNamespace: true

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: autoscaler
  url: https://kubernetes.github.io/autoscaler
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: metrics-server
    chart: stable/metrics-server

  - name: cluster-autoscaler
    chart: autoscaler/cluster-autoscaler-chart
    values:
      - "../values/cluster-autoscaler.yaml"

  - name: nginx-ingress-controller
    chart: ingress-nginx/ingress-nginx
    values:
      - "../values/nginx-ingress-controller.yaml"
