dh-ips:
    token: ENC[AES256_GCM,data:Y5W9VA7HVNtYFFiQK9jZ3g==,iv:6t2z8yJ/1+cOEH6qvjh2OzV4Wycxisy4gSiOnFTIFDI=,tag:29qaD2Pgo0ZIoDPn04KPJg==,type:str]
eks-roles:
    infra:
        username: ENC[AES256_GCM,data:T4XPRes=,iv:/IhnsTtSutBUnORPtr4KFdMCli2QZVy6E1EhADdarb4=,tag:WuLQSWUBEwc8lZQWuFJIqw==,type:str]
        role: ENC[AES256_GCM,data:Aa0ZCgdtMYy8iHXh3zPsoGRBMgMS50GjOQPJhUscPz47OtCmYrIuGj8yY/t5ZEvdbI9GeJNSFk3h,iv:SwBnjhqln2wZQ8Lavw/M1snuHryz915ZaI9X2pMcFz4=,tag:aC5DCuFDMSWGVlmGrdns3w==,type:str]
        groups:
        - ENC[AES256_GCM,data:FYpKZnUF+lPGWeflPS8=,iv:AcCGdUuWz5Ci72Huf2bJAueMKA2GeqXh+fBYrjiQ6PY=,tag:5k3pAyRKtZROt3kZv5rRww==,type:str]
jumphost:
    public-ssh-key: ENC[AES256_GCM,data:HgjqhNaXpNausfcFPkaB6g2rVnX0iO1vkS74rI7yBUcqtj4r5qODPiXhBauANF9sBw5yesV9P6xg+UV6Vw2zACU4sSnkGID+bAb6luxT5TeqnWVzicsXVl+JzyiSLKi75U7ci5lgSm0l6p/9pfBsHPEMzYyBY4lZIhDTC8cWt3B2d+YXOC8hGu+jKOzmSdaDc/LKZgLLCYm5F1frwi8zses2ocvEz1IvSiU3nkdmSXvi9g1IjrxsuIIDIYIXhYdYlGilCsSw4Jjd04gLsvLVdUuhUiAH5xSe/aJ3cBem7YUTPLU79XWLQ47MsWIJFI1umRTLW8+jctMknS0Y3HHNl5C8iS7yjxPr6x3FyTr1ExOhDXcLIXnJHMpSp8VoYZiiA3qsabiJcFukb9YWQZLkNxOqhUes0ZsMQaFfmAliXLGKLguhxCIN1bOX6dcq+yXZeTlKFS/foCid2pMN7MCX0rgvuAWCWzaPocxDpo3Itv+lxi6yV6Q14IlZcBk7DpWo0Ml3yi64ht4AGM3/rg1TeO+BIpXoeRi1Gzqs8Y+hK8hshyllV2a9lq0rzE/3MTqOkfLn8kDeetG5huURwOrmCr+Ii2k/mo6e/dfu8RsaRmnQvxRzK7oygnRdk4kHDh6tqB5fP+lPy10Y0trOHKQlr+/XKRW3Pup7tiDX10/fC5eLNakmFSHMKMO9pRZIaDwpolwO6nd4aH73lM2RPdMMmQiq9KGbn1DeoNxq32i/DmeQ3VrHVES3/3PirTEJJk1lCVI2JzZczo4J4DHW9jm4+Yn5aTR+alMdaJxXv6jiuI9ZAQzI1I+x1VXxEh4WCLWPCtiMqxTj8chXQdFQWQyHmIx3jDBU4EdXYb6KqS0GIa+UqvMcfoAlKkHNGp/ipvReETtwW3vEwDxLwnBpomZUuIf++uaFo+MXJ1ekgLHDzmAS+R9yfqyVRkmvQn3hkO0BAcTXqTj7C1A2CqtK8ldgF2uQTUPI+0VL7KllMpDJSOnlJbRNq8B/JLOznA==,iv:W5di+1S85R7xyf5x8WrGSJLrFBF02eEmi1u3ASSnE+0=,tag:3Pd1XnnlFgHUGi+kK6VUbQ==,type:str]
    users:
        infra:
            sso-roles:
            - ENC[AES256_GCM,data:ip3BcsFq9CMHsjXNz20Blo5Sw2Aj4c+j4qkeEoaSHuhqD1VIUeLYaTMmyyFrsfR57vUNBVp3bQQb,iv:YOZcxEdr/9pK254g2E7VaheCTNIY/6JFDIV6Jp7e4kg=,tag:fshKWJ6F0ZqdISJR+bBaHg==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:eu-central-1:923749771369:key/14426c3b-9006-4ab7-bd08-6a2037054758
        created_at: '2020-10-19T22:46:11Z'
        enc: AQICAHhjOlk9Z0NcTiywDzPa4ZcfTXc9VCjK1qSFkljf0MwYBAG267TiyNA4TZjf6thSePHvAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzM/hFkV71VHH44UBAgEQgDvbG5VAkhq5uP5DriNyQdMXafiJznrCkX2czyERIZFJeBxphAO5Kea+/2OLjA7lrOldqvfHOZTEC11Wkw==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-10-19T22:46:11Z'
    mac: ENC[AES256_GCM,data:S20wABIS9ZVI49VJxEEyVMQdvd5jJyHBuUUx0fj1QNmTeqfI7x5QrhmgaY2O2k7CuoDRGZ4ryLaMzI7KrAtkHfP+c4WaMfDNLhQrxJetCLfJ4zh08WDf3PdpLT17c/SBHGDIbrs7j3WQShJbj5FgeIfkoLzMGzS1+1vo5HQCGuY=,iv:9nOIzRICoVtrTKfdMVC4GmbyR81di2un1Shz5Gr6Ht8=,tag:MdLkgTpKZmGhVDUvJ9onKA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
