controller:
  replicaCount: 3
  service:
    annotations:
      "external-dns.alpha.kubernetes.io/hostname": "gateway.dh-nerddays-demo.com"
      "kubernetes.io/external-dns": "true"
      "service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "True"
      "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "http"
      "service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled": "True"
      "service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout": "60"
      "service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout": "60"

  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi

defaultBackend:
  enabled: true
