controller:
  replicaCount: 3
  service:
    annotations:
      "external-dns.alpha.kubernetes.io/hostname": "gateway.dh-nerddays-demo.com"
      "kubernetes.io/external-dns": "true"

  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi

defaultBackend:
  enabled: true
